service: api-tts
frameworkVersion: '4.1.10'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${env:DYNAMOTABLENAME}  

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:Scan'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: 
        - ${env:DYNAMOTABLEARN}  

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  post:
    handler: handler.post
    events:
      - httpApi:
          path: /v1/tts
          method: post

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-pollyPhrases-${sls:stage}  

custom:
  dotenv:
    path: .env
